pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Keeps HyDE's rofi (keybindings, wallpaper picker, theme, animations, clipboard…)
// looking like the shell's panels: the same background and opacity, the same subtle outline (instead
// of the accent-colored border) and the same selection color as the launcher.
//
// All HyDE styles import ~/.config/rofi/theme.rasi, which HyDE rewrites on every theme
// change. The shell writes it with its own colors whenever the palette changes and writes it again if HyDE
// replaces it (the file is generated and not in the repository).
Singleton {
    id: root

    readonly property string path: `${Quickshell.env("XDG_CONFIG_HOME") || Quickshell.env("HOME") + "/.config"}/rofi/theme.rasi`
    property string written: ""

    function hex(c, a) {
        const h = v => Math.round(v * 255).toString(16).padStart(2, "0");
        return `#${h(c.r)}${h(c.g)}${h(c.b)}${h(a ?? 1)}`;
    }

    function rasi() {
        const r = Theme.toRoles;
        return `/* Generated by the Quickshell shell (services/Rofi.qml): the colors of the shell's panels. */
* {
    main-bg:            ${hex(r.surfaceContainer, 0.96)};
    main-fg:            ${hex(r.text)};
    main-br:            ${hex(r.outlineVariant, 0.6)};
    main-ex:            ${hex(r.primary)};
    select-bg:          ${hex(r.primaryContainer)};
    select-fg:          ${hex(r.onPrimaryContainer)};
    separatorcolor:     transparent;
    border-color:       transparent;
}
`;
    }

    function apply() {
        const text = rasi();
        if (file.text() === text)
            return;
        written = text;
        file.setText(text);
    }

    Connections {
        target: Theme
        function onToRolesChanged() {
            root.apply();
        }
    }

    FileView {
        id: file
        path: root.path
        watchChanges: true
        printErrors: false
        blockLoading: true
        // HyDE wrote its own (theme change): the shell's is restored.
        onFileChanged: {
            reload();
            if (text() !== root.written)
                root.apply();
        }
    }

    Component.onCompleted: apply()
}
