pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Shell colors. Three sources (picked in the HyDE menu, in Prefs.colorSource):
//
//  - "hyde" (default): the colors each HyDE theme designed for the bar — the
//    ~/.cache/hyde/wallbash/bar.css that HyDE rewrites on every theme change (from the
//    theme's waybar.theme, or from the waybar.dcol template in wallbash mode).
//  - "wallbash": the theme's full palette, generated by the template
//    ~/.config/hyde/wallbash/always/quickshell.dcol.
//  - "wallpaper": the colors extracted from the current wallpaper (~/.cache/hyde/wall.dcol).
//
// All sources are watched: when the theme or wallpaper changes, the colors transition by themselves.
Singleton {
    id: root

    // Current HyDE palette used when no file exists (Catppuccin Macchiato).
    readonly property var fallbackCss: ({
            "main-bg": "#181926",
            "main-fg": "#cad3f5",
            "wb-act-bg": "#c6a0f6",
            "wb-act-fg": "#363a4f",
            "wb-hvr-bg": "#cad3f5",
            "wb-hvr-fg": "#363a4f"
        })

    property var themeCss: fallbackCss
    property var wallbashPalette: null
    property var wallPalette: null

    readonly property string source: Prefs.colorSource === "wallpaper" && wallPalette ? "wallpaper" : Prefs.colorSource === "wallbash" && wallbashPalette ? "wallbash" : "hyde"
    readonly property var targetRoles: ensureReadable(source === "wallpaper" ? paletteRoles(wallPalette) : source === "wallbash" ? paletteRoles(wallbashPalette) : cssRoles(themeCss))

    // Each color is a blend between the previous and the new colors, driven by `progress`:
    // a single animation transitions all of them (many Behaviors in a singleton crash Qt).
    property var fromRoles: cssRoles(fallbackCss)
    property var toRoles: cssRoles(fallbackCss)
    property real progress: 1

    readonly property bool dark: luminance(surface) < 0.5

    // Semantic roles (Material 3-style names).
    readonly property color surface: mix("surface")
    readonly property color surfaceContainer: mix("surfaceContainer")
    readonly property color surfaceContainerHigh: mix("surfaceContainerHigh")
    readonly property color surfaceContainerHighest: mix("surfaceContainerHighest")
    readonly property color text: mix("text")
    readonly property color textDim: mix("textDim")
    readonly property color textFaint: mix("textFaint")
    readonly property color outline: mix("outline")
    readonly property color outlineVariant: mix("outlineVariant")
    readonly property color primary: mix("primary")
    readonly property color onPrimary: mix("onPrimary")
    readonly property color primaryContainer: mix("primaryContainer")
    readonly property color onPrimaryContainer: mix("onPrimaryContainer")
    readonly property color secondary: mix("secondary")
    readonly property color tertiary: mix("tertiary")
    // Status colors: fixed base, adjusted to be readable on the theme background (light or dark).
    readonly property color error: readable("#f38ba8", surface, 3)
    readonly property color warning: readable("#f9e2af", surface, 3)
    readonly property color success: readable("#a6e3a1", surface, 3)

    // State layers (hover/press) on top of any surface.
    readonly property color hover: Qt.alpha(text, 0.08)
    readonly property color pressed: Qt.alpha(text, 0.12)

    // --- Design system -------------------------------------------------------------------------
    // Every panel uses these values (no magic numbers): the same spacing rhythm, the
    // same type scale and the same shapes across the whole shell. The bar has its own scale,
    // which follows the chosen height (BarLayout).

    // Spacing, on a 4 px grid.
    readonly property int space1: 4
    readonly property int space2: 8
    readonly property int space3: 12
    readonly property int space4: 16
    readonly property int space5: 20
    readonly property int space6: 24

    // Type scale (sizes in logical px).
    readonly property int labelSmall: 11
    readonly property int labelMedium: 12
    readonly property int labelLarge: 13
    readonly property int bodySmall: 12
    readonly property int bodyMedium: 13
    readonly property int titleSmall: 14
    readonly property int titleMedium: 16
    readonly property int titleLarge: 20
    readonly property int headline: 24
    readonly property int displaySmall: 36
    readonly property int display: 56

    // Shapes: corner radii, from the smallest (list rows) to whole panels.
    readonly property int shapeSmall: 10
    readonly property int shapeMedium: 14
    readonly property int shapeLarge: 20
    readonly property int shapeXL: 28

    // Thin outline, the same on every floating surface.
    readonly property color border: Qt.alpha(outlineVariant, 0.6)

    function alpha(color, a) {
        return Qt.alpha(color, a);
    }

    function luminance(c) {
        return 0.2126 * c.r + 0.7152 * c.g + 0.0722 * c.b;
    }

    // --- Contrast (WCAG 2) --------------------------------------------------------------------
    // HyDE themes don't always guarantee contrast between text and background (especially light ones),
    // and the bar islands may have a different background from the theme's. All text and
    // icon colors go through readable(), which darkens or lightens them just enough to be readable.

    function relativeLuminance(c) {
        c = Qt.color(c);
        const lin = v => v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
        return 0.2126 * lin(c.r) + 0.7152 * lin(c.g) + 0.0722 * lin(c.b);
    }

    function contrast(a, b) {
        const la = relativeLuminance(a), lb = relativeLuminance(b);
        return (Math.max(la, lb) + 0.05) / (Math.min(la, lb) + 0.05);
    }

    // Returns `fg` if it already has the minimum contrast against `bg`; otherwise moves it towards black or white
    // (whichever contrasts more with the background) until it gets there, keeping the hue as much as possible.
    function readable(fg, bg, minRatio) {
        fg = Qt.color(fg);
        bg = Qt.color(bg);
        const ratio = minRatio ?? 4.5;
        if (contrast(fg, bg) >= ratio)
            return fg;
        const target = contrast("#000000", bg) > contrast("#ffffff", bg) ? "#000000" : "#ffffff";
        for (let t = 0.1; t < 1; t += 0.1) {
            const c = blend(fg, target, t);
            if (contrast(c, bg) >= ratio)
                return Qt.rgba(c.r, c.g, c.b, fg.a);
        }
        return Qt.color(target);
    }

    // Final readability pass over a theme's roles.
    function ensureReadable(r) {
        r.text = readable(r.text, r.surface, 4.5);
        r.textDim = readable(r.textDim, r.surface, 3.5);
        r.textFaint = readable(r.textFaint, r.surface, 2.6);
        r.primary = readable(r.primary, r.surface, 3);
        r.onPrimary = readable(r.onPrimary, r.primary, 4.5);
        r.onPrimaryContainer = readable(r.onPrimaryContainer, r.primaryContainer, 4.5);
        r.secondary = readable(r.secondary, r.surface, 3);
        r.tertiary = readable(r.tertiary, r.surface, 3);
        return r;
    }

    // Linear blend of two colors (t = 0 → a, t = 1 → b), always opaque.
    function blend(a, b, t) {
        a = Qt.color(a);
        b = Qt.color(b);
        return Qt.rgba(a.r + (b.r - a.r) * t, a.g + (b.g - a.g) * t, a.b + (b.b - a.b) * t, 1);
    }

    // theme.css color with transparency (e.g. rgba(…, 0.4) in wallbash mode) composited over the
    // background, to get the color actually seen.
    function flatten(c, over) {
        c = Qt.color(c);
        return c.a >= 0.99 ? Qt.rgba(c.r, c.g, c.b, 1) : blend(over, Qt.rgba(c.r, c.g, c.b, 1), c.a);
    }

    // Qt doesn't understand "rgba(r, g, b, a)" with 0..255 components; it is converted here.
    function cssColor(v) {
        const m = /^rgba?\(([^)]*)\)$/.exec(String(v).trim());
        if (!m)
            return Qt.color(v);
        const p = m[1].split(",").map(s => parseFloat(s));
        return Qt.rgba(p[0] / 255, p[1] / 255, p[2] / 255, p.length > 3 ? p[3] : 1);
    }

    // The HyDE theme only defines the main bar colors; the intermediate shades are derived from them.
    function cssRoles(css) {
        const get = k => cssColor(css[k] ?? fallbackCss[k]);
        const surface = flatten(get("main-bg"), "#000000");
        const text = flatten(get("main-fg"), surface);
        const primary = flatten(get("wb-act-bg"), surface);
        const onPrimary = flatten(get("wb-act-fg"), primary);
        const hoverBg = flatten(get("wb-hvr-bg"), surface);
        return {
            "surface": surface,
            "surfaceContainer": blend(surface, text, 0.06),
            "surfaceContainerHigh": blend(surface, text, 0.1),
            "surfaceContainerHighest": blend(surface, text, 0.16),
            "text": text,
            "textDim": blend(text, surface, 0.22),
            "textFaint": blend(text, surface, 0.38),
            "outline": blend(surface, text, 0.32),
            "outlineVariant": blend(surface, text, 0.18),
            "primary": primary,
            "onPrimary": onPrimary,
            "primaryContainer": blend(surface, primary, 0.32),
            "onPrimaryContainer": blend(text, primary, 0.15),
            "secondary": hoverBg,
            "tertiary": blend(primary, text, 0.35)
        };
    }

    // Wallbash palette: 4 groups (pry1..4, from dominant to accent), each with a contrast text
    // (txtN) and 9 shades (NxaM) going from the background shade (xa1) to the text shade (xa9), in both
    // dark and light mode.
    function paletteRoles(p) {
        const get = k => Qt.color(p[k] ?? "#ff00ff");
        return {
            "surface": get("pry1"),
            "surfaceContainer": get("1xa1"),
            "surfaceContainerHigh": get("1xa2"),
            "surfaceContainerHighest": get("1xa3"),
            "text": get("txt1"),
            "textDim": get("1xa7"),
            "textFaint": get("1xa6"),
            "outline": get("1xa4"),
            "outlineVariant": get("1xa3"),
            "primary": get("4xa7"),
            "onPrimary": get("4xa1"),
            "primaryContainer": get("4xa3"),
            "onPrimaryContainer": get("4xa9"),
            "secondary": get("2xa7"),
            "tertiary": get("3xa7")
        };
    }

    function mix(role) {
        const a = fromRoles[role], b = toRoles[role], t = progress;
        return Qt.rgba(a.r + (b.r - a.r) * t, a.g + (b.g - a.g) * t, a.b + (b.b - a.b) * t, a.a + (b.a - a.a) * t);
    }

    // New colors: start from the ones on screen right now (even midway through another transition).
    onTargetRolesChanged: {
        const current = {};
        for (const role in targetRoles)
            current[role] = root[role];
        fromRoles = current;
        toRoles = targetRoles;
        progress = 0;
        transition.restart();
    }

    function setColorSource(source) {
        Prefs.colorSource = source;
        Prefs.save();
    }

    NumberAnimation {
        id: transition
        target: root
        property: "progress"
        from: 0
        to: 1
        duration: Anim.slow
        easing.type: Easing.BezierSpline
        easing.bezierCurve: Anim.standard
    }

    // Bar colors of the HyDE theme (@define-color name value;).
    FileView {
        path: `${Quickshell.env("XDG_CACHE_HOME") || Quickshell.env("HOME") + "/.cache"}/hyde/wallbash/bar.css`
        watchChanges: true
        printErrors: false
        onFileChanged: reload()
        onLoaded: {
            const out = {};
            const re = /@define-color\s+([\w-]+)\s+([^;]+);/g;
            const css = text().replace(/\/\*[\s\S]*?\*\//g, "");
            let m;
            while ((m = re.exec(css)) !== null) {
                const v = m[2].trim();
                const value = v.startsWith("@") ? out[v.slice(1)] : v;
                if (value !== undefined)
                    out[m[1]] = value;
            }
            if (out["main-bg"])
                root.themeCss = out;
        }
    }

    FileView {
        path: `${Quickshell.env("XDG_CACHE_HOME") || Quickshell.env("HOME") + "/.cache"}/hyde/wallbash/quickshell.json`
        watchChanges: true
        printErrors: false
        onFileChanged: reload()
        onLoaded: {
            try {
                root.wallbashPalette = JSON.parse(text());
            } catch (e) {
                // Wallbash writes the file in one go; a half-written JSON only happens for an instant.
            }
        }
        onLoadFailed: root.wallbashPalette = null
    }

    // Format: dcol_pry1="23162D", dcol_1xa1="402952", dcol_mode="dark"…
    FileView {
        path: `${Quickshell.env("XDG_CACHE_HOME") || Quickshell.env("HOME") + "/.cache"}/hyde/wall.dcol`
        watchChanges: true
        printErrors: false
        onFileChanged: reload()
        onLoaded: {
            const p = {};
            const re = /^dcol_(mode|pry\d|txt\d|\dxa\d)="([^"]*)"/gm;
            const src = text();
            let m;
            while ((m = re.exec(src)) !== null)
                p[m[1]] = m[1] === "mode" ? m[2] : `#${m[2]}`;
            root.wallPalette = p.pry1 ? p : null;
        }
        onLoadFailed: root.wallPalette = null
    }
}
